#!/bin/bash

# ================= Configuration Area =================
# Public Network Bridge Name (Usually PVE's management interface)
WAN_IF="vmbr0"
# ======================================================

# Force locale settings to UTF-8
export LANG=C.UTF-8
export LC_ALL=C.UTF-8

# Configuration file paths
DB_FILE="/etc/nat_rules.db"
NFT_CONF="/etc/nftables.conf"

# Color definitions
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
NC='\033[0m'

# Check for Root privileges
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script with root privileges!${NC}"
  exit 1
fi

# Initialize database file
if [ ! -f "$DB_FILE" ]; then
    touch "$DB_FILE"
fi

# Define function to get private subnets, excluding the public bridge (usually vmbr0).
get_private_vmbr_subnets() {
    # Use 'ip route' to get the routing table
    # scope link: Show only direct routes (subnets)
    # proto kernel: Show only routes automatically generated by the kernel (created after IP config)
    ip -o -4 route show scope link proto kernel | awk '
    function is_private(ip) {
        return (ip ~ /^10\./) || \
               (ip ~ /^172\.(1[6-9]|2[0-9]|3[0-1])\./) || \
               (ip ~ /^192\.168\./)
    }

    {
        iface = ""
        for(i=1; i<=NF; i++) {
            if($i == "dev") {
                iface = $(i+1)
                break
            }
        }

        # Logic: Interface name starts with 'vmbr' AND is not 'vmbr0'
        if (iface ~ /^vmbr/ && iface != "vmbr0") {
            # $1 is the CIDR network address in the route output
            split($1, a, "/")
            ip = a[1]
            if (is_private(ip)) {
                print $1
            }
        }
    }'
}

# Get all matching subnets
SUBNETS=$(get_private_vmbr_subnets)

# Check if subnets were found
if [ -z "$SUBNETS" ]; then
    echo -e "${RED}No private subnets detected on vmbr*. Script stopped. Cannot configure port forwarding for NAT VMs.${NC}"
    echo -e "${RED}Common private ranges: 10.0.0.0/8; 172.16.0.0/12; 192.168.0.0/16;${NC}"
    exit 0
else
    echo -e "${CYAN}Detected the following private subnets:${NC}"
    for cidr in $SUBNETS; do
        echo "$cidr"
    done
fi

# Ensure kernel forwarding is enabled and Nftables starts on boot
setup_forwarding_env() {
    # If file doesn't exist (-f) OR (||) configuration is missing, write it
    if [ ! -f /etc/sysctl.conf ] || ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf; then
        echo "Kernel forwarding not enabled. Writing configuration..."
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        sysctl -p /etc/sysctl.conf > /dev/null
    fi
    
    # Check if nftables is enabled on boot
    if ! systemctl is-enabled --quiet nftables; then
        echo "Nftables not enabled on boot. Enabling now..."
        systemctl enable nftables > /dev/null 2>&1
    fi
}

# Core function: Generate and apply nftables config from database. This will overwrite nftables.conf
apply_rules() {
    cat > "$NFT_CONF" <<EOF
#!/usr/sbin/nft -f

flush ruleset

table ip nat {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        
EOF

    # Generate NAT (DNAT) rules
    while IFS='|' read -r lport backend_ip backend_port proto remark status whitelist; do
        if [[ -n "$lport" ]]; then
            # status: 1=Enabled, 0=Paused (Default is 1 if empty)
            current_status=${status:-1}
            remark_text=${remark:-None}
            current_whitelist=${whitelist// /}
            # Write to config only if status is 1
            if [ "$current_status" == "1" ]; then
                # Add comments to config file for debugging
                echo "        # Remark: $remark_text" >> "$NFT_CONF"

                limit_str=""
                if [[ -n "$current_whitelist" ]]; then
                    # Replace Chinese comma with English comma
                    safe_whitelist=${current_whitelist//，/,}

                    # Check if string contains comma
                    if [[ "$safe_whitelist" == *","* ]]; then
                        # Contains comma, treat as IP list, add braces
                        limit_str="ip saddr { $safe_whitelist } "
                    else
                        # No comma, treat as single IP, no braces
                        limit_str="ip saddr $safe_whitelist "
                    fi
                fi
                
                # Query Routing Table (FIB): Check if packet destination IP (daddr) belongs to the host (PVE) itself?
                # If destination IP is local, it will be matched and forwarded by the following DNAT rules.
                if [ "$proto" == "tcp+udp" ]; then
                    echo "        fib daddr type local ${limit_str}tcp dport $lport dnat to $backend_ip:$backend_port" >> "$NFT_CONF"
                    echo "        fib daddr type local ${limit_str}udp dport $lport dnat to $backend_ip:$backend_port" >> "$NFT_CONF"
                else
                    echo "        fib daddr type local ${limit_str}$proto dport $lport dnat to $backend_ip:$backend_port" >> "$NFT_CONF"
                fi
                echo "" >> "$NFT_CONF"
            fi
        fi
    done < "$DB_FILE"

    cat >> "$NFT_CONF" <<EOF
    }

    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        
        # [CRITICAL: Only masquerade traffic going out to public network]
        # Based on private subnets, only change source IP to host IP when packets exit via public interface.
EOF

    # Masquerade traffic from private subnets accessing the internet.
    for cidr in $SUBNETS; do
        echo "        ip saddr $cidr oifname \"$WAN_IF\" masquerade" >> "$NFT_CONF"
    done

    cat >> "$NFT_CONF" <<EOF
    }
}

table ip filter {
    chain input { type filter hook input priority 0; policy accept; }
    
    chain forward { 
        # Change default policy to drop (Deny all forwarding)
        type filter hook forward priority 0; policy drop;
        
        # Allow return packets for established connections (Critical!). Without this, return traffic is blocked.
        ct state established,related accept
        
        # Configure rules for internal communication and internet access based on private subnets.
EOF

    # Allow private subnets to access each other. Remove if isolation is required.
    for cidr in $SUBNETS; do
        echo "        ip saddr $cidr ip daddr $cidr ct state new accept" >> "$NFT_CONF"
    done
    echo "" >> "$NFT_CONF"

    # Allow private subnets to access public network (Stateless, suitable for network testing).
    for cidr in $SUBNETS; do
        echo "        ip saddr $cidr oifname \"$WAN_IF\" accept" >> "$NFT_CONF"
    done
    echo "" >> "$NFT_CONF"

    # Generate Filter (Forward) Whitelist Rules
    # Note: Forward chain matches the Destination IP (Backend IP) and Port AFTER DNAT.
    while IFS='|' read -r lport backend_ip backend_port proto remark status whitelist; do
        if [[ -n "$lport" ]]; then
            # status: 1=Enabled, 0=Paused (Default is 1 if empty)
            current_status=${status:-1}
            remark_text=${remark:-None}
            current_whitelist=${whitelist// /}
            # Write to config only if status is 1
            if [ "$current_status" == "1" ]; then
                # Add comments to config file for debugging
                echo "        # Remark: $remark_text" >> "$NFT_CONF"
                
                # Process Whitelist (for Forward)
                # If NAT layer restricts source IP, Forward layer should also have the same restriction for double security.
                limit_str=""
                if [[ -n "$current_whitelist" ]]; then
                    # Replace Chinese comma with English comma
                    safe_whitelist=${current_whitelist//，/,}

                    # Check if string contains comma
                    if [[ "$safe_whitelist" == *","* ]]; then
                        # Contains comma, treat as IP list, add braces
                        limit_str="ip saddr { $safe_whitelist } "
                    else
                        # No comma, treat as single IP or subnet, no braces
                        limit_str="ip saddr $safe_whitelist "
                    fi
                fi

                # Write Forward Rule
                # Syntax: [Src Limit] ip daddr <Backend IP> <Proto> dport <Backend Port> ct state new accept
                if [ "$proto" == "tcp+udp" ]; then
                    echo "        ${limit_str}ip daddr $backend_ip tcp dport $backend_port ct state new accept" >> "$NFT_CONF"
                    echo "        ${limit_str}ip daddr $backend_ip udp dport $backend_port ct state new accept" >> "$NFT_CONF"
                else
                    echo "        ${limit_str}ip daddr $backend_ip $proto dport $backend_port ct state new accept" >> "$NFT_CONF"
                fi
                echo "" >> "$NFT_CONF"
            fi
        fi
    done < "$DB_FILE"

    cat >> "$NFT_CONF" <<EOF
    }
    chain output { type filter hook output priority 0; policy accept; }
}
EOF

    # Choose command based on Nftables service status
    if systemctl is-active --quiet nftables; then
        # Reload config if active
        systemctl reload nftables
    else
        # Restart service if stopped
        systemctl restart nftables
    fi
    
    local error_status=$?
    
    if [ $error_status -eq 0 ]; then
        echo -e "${GREEN}Configuration updated and applied!${NC}"
        return 0
    else
        echo -e "${RED}Failed to apply configuration. Please check input validity.${NC}"
        # Output last few lines of error log for debugging
        echo -e "${YELLOW}Error Details (journalctl):${NC}"
        journalctl -xeu nftables.service | tail -n 10
        return 1
    fi
}

# --- Public Function: Print Rules Table ---
# Arg $1: Filter mode (all, enabled, paused)
# Return: 0=Data shown, 1=No data shown
show_rules_table() {
    local filter_mode=$1
    local found_count=0
    
    if [ ! -s "$DB_FILE" ]; then
        echo "No rules found."
        return 1
    fi

    # Unified Header
    printf "${YELLOW}%-4s %-8s %-10s %-12s %-16s %-12s %-12s %-s${NC}\n" "ID" "Status" "Proto" "LocalPort" "Dest IP" "Dest Port" "Src Limit" "Remark"
    echo "------------------------------------------------------------------------------------------------"

    local i=1
    while IFS='|' read -r lport backend_ip backend_port proto remark status whitelist; do
        current_status=${status:-1}
        safe_remark=${remark:-"-"}
        
        # Determine if row should be shown
        local show_row=0
        if [ "$filter_mode" == "all" ]; then show_row=1; fi
        if [ "$filter_mode" == "enabled" ] && [ "$current_status" == "1" ]; then show_row=1; fi
        if [ "$filter_mode" == "paused" ] && [ "$current_status" == "0" ]; then show_row=1; fi

        if [ $show_row -eq 1 ]; then
            # Status color
            if [ "$current_status" == "1" ]; then
                status_str="${GREEN}Active${NC}"
            else
                status_str="${RED}Paused${NC}"
            fi

            # Whitelist display
            if [[ -n "$whitelist" ]]; then
                wl_display="Yes"
            else
                wl_display="No"
            fi

            # Print row
            printf "%-4s %-19b %-10s %-8s %-16s %-8s %-9s %-s\n" "$i" "$status_str" "$proto" "$lport" "$backend_ip" "$backend_port" "$wl_display" "$safe_remark"
            found_count=$((found_count + 1))
        fi
        
        # Increment line number regardless of display to match ID with file line number
        ((i++))
    done < "$DB_FILE"
    echo "======================"

    if [ $found_count -eq 0 ]; then
        if [ "$filter_mode" == "enabled" ]; then echo "No active rules."; fi
        if [ "$filter_mode" == "paused" ]; then echo "No paused rules."; fi
        return 1
    fi
    return 0
}

# 1. List All Rules
list_rules() {
    echo -e "\n${CYAN}=== Current Rule List ===${NC}"
    show_rules_table "all"
}

# 2. Add Forwarding Rule
add_rule() {
    echo -e "\n${GREEN}>>> Add New Forwarding Rule${NC}"
    
    read -p "Local Listening Port (e.g., 8080): " lport
    read -p "Backend Real IP (e.g., 192.168.1.20): " backend_ip
    read -p "Backend Real Port (e.g., 80): " backend_port
    
    echo "Protocol Type:"
    echo "1) TCP"
    echo "2) UDP"
    echo "3) TCP + UDP"
    read -p "Select (1-3): " p_choice
    
    case $p_choice in
        1) proto="tcp" ;;
        2) proto="udp" ;;
        3) proto="tcp+udp" ;;
        *) echo -e "${RED}Invalid selection${NC}"; return ;;
    esac

    read -p "Remark (Optional, do not use '|' symbol): " user_remark
    # Remove pipe symbols that might break formatting
    user_remark=${user_remark//|/}
    
    echo -e "\n${YELLOW}Set Allowed Source IPs (Whitelist)${NC}"
    echo "Format = 1.1.1.1,192.168.1.0/24 (Comma separated); Empty = Allow All."
    read -p "Enter: " whitelist_input
    whitelist_input=${whitelist_input// /}
    whitelist_input=${whitelist_input//|/}
    whitelist_input=${whitelist_input//，/,}

    # Use awk for smarter protocol conflict detection
    # Logic:
    # 1. Check only if port matches (Col 1 == lport)
    # 2. If existing proto == new proto -> Conflict
    # 3. If existing proto == "tcp+udp" -> Conflict with anything
    # 4. If new proto == "tcp+udp" -> Conflict if any rule exists on port
    
    conflict_check=$(awk -F"|" -v new_port="$lport" -v new_proto="$proto" '
    $1 == new_port {
        if ($4 == new_proto || $4 == "tcp+udp" || new_proto == "tcp+udp") {
            print "1"
            exit
        }
    }' "$DB_FILE")

    if [ "$conflict_check" == "1" ]; then
        echo -e "${RED}Error: Protocol conflict on local port $lport!${NC}"
        echo -e "${YELLOW}Hint: The Port+Proto you are adding conflicts with an existing rule. Do not add duplicates.${NC}"
        return
    fi
    
    # Backup original config
    cp "$DB_FILE" "${DB_FILE}.bak"
    
    echo "$lport|$backend_ip|$backend_port|$proto|$user_remark|1|$whitelist_input" >> "$DB_FILE"
    apply_rules
    
    # Exception handling mechanism
    if [ $? -ne 0 ]; then
        echo -e "${YELLOW}>>> Configuration error detected. Auto-rolling back...${NC}"
        mv "${DB_FILE}.bak" "$DB_FILE" # Restore backup
        apply_rules > /dev/null 2>&1   # Re-apply old correct config
        echo -e "${GREEN}Rollback complete. New rule revoked. Please check if service is running normally.${NC}"
    else
        rm -f "${DB_FILE}.bak" # Delete backup if successful
    fi
}

# Internal Function: Pause Rule
pause_rule_logic() {
    echo -e "\n${CYAN}>>> Pause Forwarding Rule${NC}"
    echo -e "(Showing currently [Active] rules only)"
    
    # Call public function to show "enabled" rules and get return value
    if ! show_rules_table "enabled"; then
        return
    fi

    read -p "Enter Rule ID to [Pause]: " target_id
    
    total_lines=$(wc -l < "$DB_FILE")
    if [[ "$target_id" =~ ^[0-9]+$ ]] && [ "$target_id" -le "$total_lines" ] && [ "$target_id" -gt 0 ]; then
        awk -v line="$target_id" -v FS="|" -v OFS="|" 'NR==line {$6="0"} {print}' "$DB_FILE" > "${DB_FILE}.tmp" && mv "${DB_FILE}.tmp" "$DB_FILE"
        echo -e "${YELLOW}Rule ID $target_id has been paused.${NC}"
        apply_rules
    else
        echo -e "${RED}Invalid ID${NC}"
    fi
}

# Internal Function: Enable Rule
enable_rule_logic() {
    echo -e "\n${CYAN}>>> Enable Forwarding Rule${NC}"
    echo -e "(Showing currently [Paused] rules only)"
    
    # Call public function to show "paused" rules and get return value
    if ! show_rules_table "paused"; then
        return
    fi

    read -p "Enter Rule ID to [Enable]: " target_id
    
    total_lines=$(wc -l < "$DB_FILE")
    if [[ "$target_id" =~ ^[0-9]+$ ]] && [ "$target_id" -le "$total_lines" ] && [ "$target_id" -gt 0 ]; then
        awk -v line="$target_id" -v FS="|" -v OFS="|" 'NR==line {$6="1"} {print}' "$DB_FILE" > "${DB_FILE}.tmp" && mv "${DB_FILE}.tmp" "$DB_FILE"
        echo -e "${GREEN}Rule ID $target_id has been re-enabled.${NC}"
        apply_rules
    else
        echo -e "${RED}Invalid ID${NC}"
    fi
}

# 3. Manage Rule State (Sub-menu)
manage_state() {
    echo -e "\n${YELLOW}>>> Manage Rule State${NC}"
    echo "1. Pause Rule"
    echo "2. Enable Rule"
    echo "3. Return to Main Menu"
    read -p "Select Operation [1-3]: " sub_choice
    
    case $sub_choice in
        1) pause_rule_logic ;;
        2) enable_rule_logic ;;
        3) return ;;
        *) echo "Invalid Input" ;;
    esac
}

# 4. Delete Forwarding Rule
del_rule() {
    echo -e "\n${RED}>>> Delete Forwarding Rule${NC}"
    # Use 'all' mode here so user can view all rules before deleting
    if ! show_rules_table "all"; then
        return
    fi
    
    read -p "Enter Rule ID to Delete: " del_id
    total_lines=$(wc -l < "$DB_FILE")
    
    if [[ "$del_id" =~ ^[0-9]+$ ]] && [ "$del_id" -le "$total_lines" ] && [ "$del_id" -gt 0 ]; then
        sed -i "${del_id}d" "$DB_FILE"
        apply_rules
    else
        echo -e "${RED}Invalid ID${NC}"
    fi
}

# 5. Restore/Reload Configuration
restore_config() {
    echo -e "\n${YELLOW}>>> Restoring configuration...${NC}"
    # Check if database has content
    if [ ! -s "$DB_FILE" ]; then
        echo -e "${RED}Error: Database file (/etc/nat_rules.db) is empty or missing. Cannot restore.${NC}"
        echo -e "Please add at least one rule first."
        return
    fi
    # Force call apply_rules to rewrite and restart
    echo "Reading database and rewriting nftables configuration file..."
    apply_rules
}

# Main Menu
setup_forwarding_env
while true; do
    echo -e "\n${CYAN}PVE Transparent Forwarding Manager (nftables)${NC}"
    if systemctl is-active --quiet nftables; then
        nft_status="${GREEN}● Running${NC}"
    else
        nft_status="${RED}● Stopped${NC}"
    fi
    echo -e "Service Status: ${nft_status}${NC}"
    echo "1. List All Rules"
    echo "2. Add Forwarding Rule"
    echo "3. Pause/Enable Rule"
    echo "4. Delete Forwarding Rule"
    echo "5. Restore/Reload Config"
    echo "6. Exit"
    read -p "Enter Option [1-6]: " choice

    case $choice in
        1) list_rules ;;
        2) add_rule ;;
        3) manage_state ;;
        4) del_rule ;;
        5) restore_config ;;
        6) exit 0 ;;
        *) echo "Invalid Input" ;;
    esac
done